//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_prog3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {
        public Empleado()
        {
            this.Departamentos = new HashSet<Departamento>();
            this.Licencias = new HashSet<Licencia>();
            this.Permisos = new HashSet<Permiso>();
            this.SalidaEmpleados = new HashSet<SalidaEmpleado>();
            this.Vacaciones = new HashSet<Vacacione>();
        }

        public int Id { get; set; }
        [Required]
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string genero { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<int> Cargo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public decimal Salario { get; set; }
        public string estatus { get; set; }

        public virtual Cargo Cargo1 { get; set; }

        public virtual ICollection<Departamento> Departamentos { get; set; }
        public virtual ICollection<Licencia> Licencias { get; set; }
        public virtual ICollection<Permiso> Permisos { get; set; }
        public virtual ICollection<SalidaEmpleado> SalidaEmpleados { get; set; }
        public virtual ICollection<Vacacione> Vacaciones { get; set; }
    }
}
