//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_prog3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Permiso
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Se necesita el codigo del empleado")]
        public int IdEmpleado { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Se necesita la fecha de inicio")]
        public DateTime Desde { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Se necesita la fecha de fin")]
        public DateTime Hasta { get; set; }

        [Required]
        [MaxLength(100, ErrorMessage = "Solo son permitidos 100 Caracteres")]
        public string Comentarios { get; set; }

        public virtual Empleado Empleado { get; set; }
    }
}
