//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_prog3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaEmpleado
    {
        public int Id { get; set; }
        public int IdEmpleado { get; set; }
        public string TipoSalida { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaSalida { get; set; }
    }
}
