//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_prog3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SalidaEmpleado
    {
        public int Id { get; set; }


        [Required(ErrorMessage = "Se necesita el Codigo del empleado")]

        public int IdEmpleado { get; set; }

        [Required(ErrorMessage = "Se necesita el tipo de salida")]
        public string TipoSalida { get; set; }

        public string Motivo { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Se necesita la fecha de salida")]
        public DateTime FechaSalida { get; set; }

        public virtual Empleado Empleado { get; set; }
    }


}
